name: Build + Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.git**'
      - 'service/**'
      - '**.md'
      - 'LICENSE'
  workflow_dispatch:
    inputs:
      version:
        description: 'release version'
        required: false
        default: 'latest'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: setup nodejs
        uses: actions/setup-node@main
        with:
          node-version: 'latest'

      - name: processing
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # building and compressing
          npm run build
          tar -zcvf "./moneybook.tar.gz" -C "dist" index.js

          # delete all releases and their tags
          gh release list | awk -F '\t' '{print $3}' | while read -r line; do gh release delete --yes --cleanup-tag "$line"; done

          # create release
          if [ "${{ inputs.version }}" != "" ]; then
            tag="${{ inputs.version }}"
          else
            tag=latest
          fi
          gh release create "$tag" --generate-notes "./moneybook.tar.gz"
